server:
  port: 9191

spring:
  application:
    name: SERVICE-GATEWAY
  cloud:
    gateway:
      routes:
        - id: resources
          uri: http://user-service:8082/messages
          predicates:
            Path=/messages/**
          filters:
            TokenRelay=
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: my_client
            client-secret: 4yu03qyPqL51fQk2l94DEGUSN5PyFGgI
            authorization-grant-type: authorization_code
            redirect-uri: "http://service-gateway:9191/login/oauth2/code/{registrationId}"
            scope: openid, message.read
        provider:
          my-provider:
            issuer-uri: http://auth-keycloak:8085/auth/realms/my_realm